### ISSUE TITLE
Trying to get it to work on Ubuntu 20.10 Node v14.16.0: login always fails

### ISSUE THREAD

**Issue by cirosantilli** [pedrogk/feathers-chat-sequelize#1]
Thanks for this repo, first it was hanging after signup button, updated PostgreSQL dependencies at https://github.com/cirosantilli/feathers-chat-sequelize/commit/b5536ea52eb83e528c3e603aeda12bd35d99ba9e and it started inserting users in DB.

But now login fails, redirects to failed login page. I'll update this if I ever solve it

Have you found any better Node.js web framework since BTW Pedro? Stuff that seemed should be basic hello worlds fails without extensive on all I've tried so far.

**Comment by cirosantilli** [comment]
Oh, I managed a setup by forking the original chat app and using inspiration from this repo: https://github.com/cirosantilli/feathers-chat/tree/sequelize-pg

**Comment by pedrogk** [comment]
I haven't done anything with feathers for a while. I don't know if it is still active or not.
